name: Tests
on:
  push:
    branches: ['develop', 'release-*']
jobs:
  ci:
    name: Test - Unit & Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: {fetch-depth: 0}
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Unit & Integration Tests
        run: mvn -B verify
      - name: Sonar
        if: success()
        run: >
          mvn -B verify -DskipTests sonar:sonar
          -Dsonar.projectKey=alu0101320489_iwvg-devops-Hernandez-Daniel
          -Dsonar.organization=alu0101320489
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
